### ISSUE TITLE
DRAFT: Random Improvent Proposal Ideas

### ISSUE THREAD

**Issue by thet** [conestack/yafowil#30]
This is a work in progress for improvement ideas, coming up as I work with YAFOWIL.

- factory widget properties: allow namespaces:

Currently, if you want to create a label, an error div and a text field with a factory and want the label contain the textfield, you do it like so:
```
factory(
    'label:error:text',
    props={
        'label': _('label_minute', u'Minute'),
        'position': 'inner-before'
    }
)


```
the ``error`` blueprint also accepts a ``position`` property and it is not clear to which one it belongs.
I propose to allow nested dicts:
```
factory(
    'label:error:text',
    props={
        'label': {
            'text': _('label_minute', u'Minute'),
            'position': 'inner-before'
        }
    }
)
```
this should also be possible to support with YAML.

- ...

**Comment by rnixx** [comment]
properties already support namespaces

http://docs.yafowil.info/architecture.html#combining-blueprints-the-factory-chain

E.g., ‘label.class’ addresses the ‘class’ property of the ‘label’ blueprint only instead of effecting all blueprints:

form['field_1'] = factory('field:label:error:text', props={
    'label': 'Field 1',
    'label.class': 'label_css_class'
    'help': 'Helptext for field 1',
    'required': 'Field 1 must not be empty',
})

**Comment by thet** [comment]
Stale issue.
